#!/usr/bin/env python
# -*- coding: ISO-8859-1 -*-
# generated by wxGlade 0.3.4 on Tue Aug 17 19:12:17 2004

import wx, pysvn

class MyFrame(wx.Frame):
	def __init__(self, *args, **kwds):
		# begin wxGlade: MyFrame.__init__
		kwds["style"] = wx.ICONIZE|wx.CAPTION|wx.CLOSE_BOX|wx.MINIMIZE_BOX|wx.SYSTEM_MENU|wx.SIMPLE_BORDER
		wx.Frame.__init__(self, *args, **kwds)
		self.list_ctrl_1 = wx.ListCtrl(self, -1, style=wx.LC_REPORT|wx.LC_HRULES|wx.SUNKEN_BORDER)
		self.combo_box_1 = wx.ComboBox(self, -1, choices=[], style=wx.CB_DROPDOWN|wx.CB_READONLY)
		self.bUpdate = wx.Button(self, -1, "Pobierz")
		
		self.__set_properties()
		self.__do_layout()
		# end wxGlade

	def __set_properties(self):
		# begin wxGlade: MyFrame.__set_properties
		self.SetTitle("communityBT updater")
		self.SetSize((471, 381))
		self.SetBackgroundColour(wx.Colour(42, 71, 128))
		self.combo_box_1.SetSelection(-1)
		self.bUpdate.SetDefault()
		# end wxGlade

	def __do_layout(self):
		# begin wxGlade: MyFrame.__do_layout
		sizer_1 = wx.FlexGridSizer(2, 1, 0, 0)
		sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
		sizer_1.Add(self.list_ctrl_1, 4, wx.EXPAND, 0)
		sizer_2.Add(self.combo_box_1, 1, wx.ALL|wx.EXPAND, 4)
		sizer_2.Add(self.bUpdate, 0, wx.ALL, 4)
		sizer_1.Add(sizer_2, 1, wx.ALL|wx.EXPAND, 0)
		self.SetAutoLayout(1)
		self.SetSizer(sizer_1)
		sizer_1.AddGrowableRow(0)
		sizer_1.AddGrowableCol(0)
		self.Layout()
		self.Centre()
		# end wxGlade

# end of class MyFrame


class MyApp(wx.App):
	def OnInit(self):
		wx.InitAllImageHandlers()
		frame_1 = MyFrame(None, -1, "")
		self.SetTopWindow(frame_1)
		frame_1.Show(1)
		return 1

# end of class MyApp

if __name__ == "__main__":
	app = MyApp(0)
	app.MainLoop()
